<a href="https://colab.research.google.com/github/EfoodCN/d2l-zh/blob/master/%E9%A2%84%E5%A4%87%E7%9F%A5%E8%AF%86(tensor_%E6%93%8D%E4%BD%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
x.shape

torch.Size([12])

In [3]:
x.numel()

12

In [4]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
X = X.reshape(-1, 3)
X

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [6]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(2, 3, 4)

tensor([[[ 0.1465,  0.1557,  0.6388, -0.3320],
         [ 0.2972,  0.0151, -0.1023,  0.8948],
         [-0.9188, -2.1675, -1.0314,  0.2597]],

        [[ 0.2168, -2.0185, -1.3989,  0.6594],
         [-1.0289, -0.8638,  0.3954, -2.2209],
         [-0.9132, -1.2187, -0.0604,  0.5966]]])

In [9]:
torch.rand(2, 3, 4)

tensor([[[0.9492, 0.8684, 0.0467, 0.2890],
         [0.7597, 0.5566, 0.4595, 0.8996],
         [0.1476, 0.0698, 0.8751, 0.0332]],

        [[0.6372, 0.5642, 0.9637, 0.3559],
         [0.5605, 0.4562, 0.9131, 0.1887],
         [0.8656, 0.8274, 0.3733, 0.7202]]])

In [10]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x, y

(tensor([1., 2., 4., 8.]), tensor([2, 2, 2, 2]))

In [13]:
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [18]:
X.shape, Y.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [21]:
# 按照哪一维度concat那一维就会改变，其他维度不变
c1, c2 = torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
c1, c2, c1.shape, c2.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]),
 torch.Size([6, 4]),
 torch.Size([3, 8]))

In [22]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
X.sum()

tensor(66.)

In [24]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(-1, 2)
a, b, a.shape, b.shape

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 torch.Size([3, 1]),
 torch.Size([1, 2]))

In [25]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
X[-1], X[0:3], X #左闭右开

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [31]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
X[0:2, :] = 2
X

tensor([[ 2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.],
        [ 8.,  9., 10., 11.]])

In [33]:
before = id(Y)
Y = X+Y
cur = id(Y)
before, cur

(137048073579280, 137050947484496)

In [34]:
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X + Y
print(id(Z))

137050947478016
137050947478016


In [35]:
before = id(X)
X += Y
id(X) == before

True

In [36]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [37]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)